/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c8733658e21cb1365152547ff51a3df5)
interface __BaseEnv_Env {
	sendio_chat_index: D1Database;
	SUPABASE_URL: "https://atlbsghwdprrfzkdpldy.supabase.co";
	CHAT_ROOM: DurableObjectNamespace<import("./src/index").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
